version: "3.9"

services:
  api:
    build: .
    container_name: rust-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rust_api
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:15
    container_name: postgres-rust
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_api
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis-rust
    ports:
      - "6379:6379"